/**
 * Script: generate SQL UPDATE for garment_variants copy columns.
 * Usage: npx tsx src/generate-copy-update.ts [--pros-only]
 */
import { generateGarmentVariants } from "./garment-variant-generator";

function sqlStr(s: string | null): string {
  if (s === null) return "null::text";
  return `'${s.replace(/'/g, "''")}'`;
}

const rows = generateGarmentVariants();
const prosOnly = process.argv.includes("--pros-only");

const valueLines = rows.map((r, i) => {
  return [
    `  (`,
    `    ${sqlStr(r.category_code)},`,
    `    ${sqlStr(r.material)},`,
    `    ${sqlStr(r.fill_type)},`,
    `    ${sqlStr(r.thickness)},`,
    `    ${sqlStr(r.fit_type)},`,
    `    ${sqlStr(r.bodysuit_style)},`,
    `    ${sqlStr(r.pant_length)},`,
    `    ${sqlStr(r.sock_height)},`,
    `    ${sqlStr(r.hat_kind)},`,
    `    ${sqlStr(r.pros)},`,
    `    ${sqlStr(r.cons)},`,
    `    ${sqlStr(r.usage_tips)}`,
    `  )${i < rows.length - 1 ? "," : ""}`,
  ].join("\n");
});

process.stdout.write(`-- Auto-generated by packages/core/src/generate-copy-update.ts\n`);
process.stdout.write(`-- ${rows.length} rows\n`);
process.stdout.write(`update public.garment_variants gv\n`);
process.stdout.write(`set\n`);
process.stdout.write(prosOnly ? `  pros = v.pros\n` : `  pros = v.pros,\n  cons = v.cons,\n  usage_tips = v.usage_tips\n`);
process.stdout.write(`from (values\n`);
process.stdout.write(valueLines.join("\n"));
process.stdout.write(`\n) as v(\n`);
process.stdout.write(`  category_code, material, fill_type, thickness, fit_type,\n`);
process.stdout.write(`  bodysuit_style, pant_length, sock_height, hat_kind, pros, cons, usage_tips\n`);
process.stdout.write(`)\n`);
process.stdout.write(`where gv.category_code = v.category_code\n`);
process.stdout.write(`  and gv.material is not distinct from v.material\n`);
process.stdout.write(`  and gv.fill_type is not distinct from v.fill_type\n`);
process.stdout.write(`  and gv.thickness is not distinct from v.thickness\n`);
process.stdout.write(`  and gv.fit_type is not distinct from v.fit_type\n`);
process.stdout.write(`  and gv.bodysuit_style is not distinct from v.bodysuit_style\n`);
process.stdout.write(`  and gv.pant_length is not distinct from v.pant_length\n`);
process.stdout.write(`  and gv.sock_height is not distinct from v.sock_height\n`);
process.stdout.write(`  and gv.hat_kind is not distinct from v.hat_kind;\n`);
