/**
 * Script: generate SQL VALUES seed for garment_variants migration.
 * Usage: npx tsx src/generate-migration-seed.ts > /tmp/seed.sql
 */
import { generateGarmentVariants } from "./garment-variant-generator";

function sqlStr(s: string | null): string {
  if (s === null) return "null";
  return `'${s.replace(/'/g, "''")}'`;
}

function sqlArr(arr: string[]): string {
  if (arr.length === 0) return "'{}'";
  return `array[${arr.map((t) => `'${t.replace(/'/g, "''")}'`).join(",")}]`;
}

const rows = generateGarmentVariants();

const lines = rows.map((r, i) => {
  return [
    `  (`,
    `    (select id from public.categories where code = ${sqlStr(r.category_code)}),`,
    `    ${sqlStr(r.category_code)},`,
    `    ${sqlStr(r.material)},`,
    `    ${sqlStr(r.fill_type)},`,
    `    ${sqlStr(r.thickness)},`,
    `    ${sqlStr(r.fit_type)},`,
    `    ${sqlStr(r.bodysuit_style)},`,
    `    ${sqlStr(r.pant_length)},`,
    `    ${sqlStr(r.sock_height)},`,
    `    ${sqlStr(r.hat_kind)},`,
    `    ${r.warmth_value},`,
    `    ${sqlStr(r.admin_label)},`,
    `    ${sqlStr(r.consumer_label)},`,
    `    ${sqlStr(r.consumer_label_en)},`,
    `    ${sqlArr(r.consumer_tags)},`,
    `    ${sqlStr(r.pros)},`,
    `    ${sqlStr(r.cons)},`,
    `    ${sqlStr(r.usage_tips)},`,
    `    ${r.is_active},`,
    `    ${r.sort_order}`,
    `  )${i < rows.length - 1 ? "," : ""}`,
  ].join("\n");
});

process.stdout.write(`-- Auto-generated by packages/core/src/generate-migration-seed.ts\n`);
process.stdout.write(`-- ${rows.length} rows\n`);
process.stdout.write(`insert into public.garment_variants\n`);
process.stdout.write(`  (category_id, category_code, material, fill_type, thickness, fit_type,\n`);
process.stdout.write(`   bodysuit_style, pant_length, sock_height, hat_kind, warmth_value,\n`);
process.stdout.write(`   admin_label, consumer_label, consumer_label_en, consumer_tags, pros, cons, usage_tips,\n`);
process.stdout.write(`   is_active, sort_order)\nvalues\n`);
process.stdout.write(lines.join("\n"));
process.stdout.write(`\n;\n`);
