-- Three-level parent-facing clothing guide content: category, style, material.
create table if not exists public.category_guide_contents (
  category_code text primary key references public.categories(code) on delete cascade,
  intro text not null check (char_length(intro) between 1 and 100),
  style_guides jsonb not null default '[]'::jsonb,
  material_guides jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint category_guide_contents_style_array check (jsonb_typeof(style_guides) = 'array'),
  constraint category_guide_contents_material_array check (jsonb_typeof(material_guides) = 'array')
);

comment on table public.category_guide_contents is 'C 端衣物介绍半弹层：品类科普、款式指南、面料指南；后台按三层维护。';

drop trigger if exists category_guide_contents_updated_at on public.category_guide_contents;
create trigger category_guide_contents_updated_at
  before update on public.category_guide_contents
  for each row execute function public.set_updated_at();

alter table public.category_guide_contents enable row level security;
drop policy if exists category_guide_contents_select_active_category on public.category_guide_contents;
create policy category_guide_contents_select_active_category
  on public.category_guide_contents for select
  using (exists (select 1 from public.categories where categories.code = category_guide_contents.category_code and categories.is_active = true));

insert into public.category_guide_contents (category_code, intro, style_guides, material_guides)
values
  ('bodysuit_short', '还在穿尿布、常被抱起或爬行时，可以考虑短袖包屁衣；开始练习自己如厕后，分体衣裤更方便。选购时留意领口开合、裆部余量和腿口包边，短袖只露出手臂，不代表整件一定凉快。', '[{"axis":"bodysuit_style","value":"triangle","name":"三角款","pros":["腿口以下没有裤腿，另搭裤子时少一层堆叠。","裆部有开扣的款式，换尿布不用把上衣整件脱下。"],"cautions":["试穿时留意腿口包边，穿着尿布也不应明显勒住大腿根。","腿部覆盖较少，是否加裤子要看环境和活动场景。"]},{"axis":"bodysuit_style","value":"long_leg","name":"长裤款","pros":["上衣和裤腿连在一起，抱起或翻身时腰间不容易露出。","需要覆盖腿部时，可少搭一条独立裤子。"],"cautions":["买前看裆部开口，只有领口开扣的款式换尿布更费事。","让宝宝屈膝、抬腿，确认裆部和裤腿没有一起绷紧。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["轻薄棉布能吸收少量汗液，适合贴身穿。"],"cautions":["吸湿后未必干得快，衣服汗湿了要及时换。","棉不等于纯棉，买前看实际成分比例。"]},{"value":"modal","name":"莫代尔","pros":["手感通常柔软、垂顺，适合偏好柔滑触感的贴身衣物。"],"cautions":["柔软不等于凉快，厚薄和织法同样影响穿着感受。","试试裆部按扣周围是否牢靠，别只摸衣身的手感。"]},{"value":"polyester","name":"涤纶","pros":["纤维吸水较少，洗后通常较容易干。"],"cautions":["涤纶不等于速干衣，导湿效果要看具体面料设计。","短袖也可能穿得闷，留意前胸、后背实际厚度。"]}]'::jsonb),
  ('bodysuit_long', '长袖包屁衣适合需要覆盖手臂、又想让上衣和裆部连在一起时穿。选领口好开合、袖口不勒手腕的款式，穿着尿布试试屈膝和抬手。是否合适看身长和活动余量，不按月龄一刀切。', '[{"axis":"bodysuit_style","value":"triangle","name":"三角款","pros":["腿口以下没有裤腿，另搭裤子时少一层堆叠。","裆部有开扣的款式，换尿布不用把上衣整件脱下。"],"cautions":["试穿时留意腿口包边，穿着尿布也不应明显勒住大腿根。","腿部覆盖较少，是否加裤子要看环境和活动场景。"]},{"axis":"bodysuit_style","value":"long_leg","name":"长裤款","pros":["上衣和裤腿连在一起，抱起或翻身时腰间不容易露出。","需要覆盖腿部时，可少搭一条独立裤子。"],"cautions":["买前看裆部开口，只有领口开扣的款式换尿布更费事。","让宝宝屈膝、抬腿，确认裆部和裤腿没有一起绷紧。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["棉布可吸收少量汗液，适合作为贴身层。"],"cautions":["洗后可能缩水，先看洗标，别买已经绷住袖子和裆部的尺码。","袖口经常被含咬或沾湿，要及时更换湿衣。"]},{"value":"modal","name":"莫代尔","pros":["布面通常柔滑，套进外衣袖子时较顺畅。"],"cautions":["混纺比例不同，弹性和厚度也不同，不能只认材质名称。","垂顺的长袖可能滑到手掌上，袖长和袖口都要试。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常容易干，频繁换洗时比较方便。"],"cautions":["吸水少不代表汗会自动排走，要看贴肤面的导湿设计。","留意腋下和袖缝，较硬的接缝可能反复磨蹭皮肤。"]}]'::jsonb),
  ('sweater', '毛衣适合作为中间层，冷热变化时方便增减。抱起、爬行的宝宝可选织面平整、少装饰的款式；挑选时摸一摸领口和袖口内侧，贴肤扎不扎比看起来蓬松更值得留意。', '[{"axis":"fit_type","value":"slim","name":"紧身版型","pros":["衣身贴合，外面套外套时占的空间较少。"],"cautions":["织物有弹性也不能一直绷着，抱臂时肩背要舒展。"]},{"axis":"fit_type","value":"regular","name":"标准版型","pros":["内穿打底、外加外套都较方便，适合叠穿。"],"cautions":["试穿要带着打底衫，单穿刚好的尺码叠穿后可能紧。"]},{"axis":"fit_type","value":"loose","name":"宽松版型","pros":["里面可容纳稍厚的打底，肩臂活动余量较大。"],"cautions":["爬行时留意长下摆和松袖口，别压在手掌下面。","外套也要有相应空间，别把毛衣挤成一团。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["棉针织便于作薄中间层，适合不喜欢毛感触感的孩子。"],"cautions":["厚棉针织吸水后较沉，洗后按洗标整理晾干。","松散织法仍会透风，不能按重量判断挡风能力。"]},{"value":"acrylic","name":"腈纶","pros":["能做出蓬松的针织手感，常用于仿毛织物。"],"cautions":["仿毛外观不等于羊毛成分，也不说明一定更暖。","腋下、袖侧容易反复摩擦，挑选时看织面是否易起毛。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常较容易干，日常打理相对方便。"],"cautions":["不能默认可高温烘干，先看洗标允许的方式。","针织衫的松紧与织法有关，别因含涤纶就默认有弹性。"]},{"value":"wool","name":"羊毛","pros":["卷曲纤维能留住空气，适合用作保暖中间层。"],"cautions":["粗细不同，贴肤触感差别很大，先试领口是否扎。","是否机洗以洗标为准，不能把所有羊毛衫都放进普通洗涤程序。"]}]'::jsonb),
  ('fleece_top', '卫衣或抓绒适合在打底衫外加一层。经常爬行、玩耍时，先看肩背和肘部能否伸展，再看袖口是否好挽。领口、帽子处不选带抽绳的款式，拉链顶端要有遮挡，避免蹭下巴。', '[{"axis":"fit_type","value":"regular","name":"标准版型","pros":["作为中间层较利落，外面套外套不易堆布。"],"cautions":["里面加了打底后再试着抬手，别让肩背被拉住。"]},{"axis":"fit_type","value":"loose","name":"宽松版型","pros":["肩背和肘部留量较多，玩耍时方便伸展。"],"cautions":["厚面料再配过长袖子会妨碍抓握，袖口应停在手腕附近。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["棉质卫衣可作日常中间层，布面与绒面有不同触感可选。"],"cautions":["厚款汗湿后较难干，玩耍出汗后摸一摸背部内侧。","“卫衣”不代表都有抓绒，要看里面实际是否起绒。"]},{"value":"fleece","name":"摇粒绒","pros":["蓬松绒面能留住空气，重量较轻，适合叠穿。"],"cautions":["普通摇粒绒不一定挡风，风大时看外层是否需要补充。","摇粒绒是面料形态，纤维成分仍要另看标签。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常较易干，适合常换洗的活动衣。"],"cautions":["是否起绒、是否导湿要分别看，不能仅凭成分推断。","贴肤侧较粗时可配打底，重点试脖颈和袖口位置。"]}]'::jsonb),
  ('vest', '马甲适合需要给躯干加一层、又想让手臂活动方便时穿。试穿要带上里面那件衣服，检查腋下是否夹紧、下摆是否上窜。它不覆盖手臂，不能只凭胸口暖和就判断全身够不够暖。', '[{"axis":"fit_type","value":"regular","name":"标准版型","pros":["贴合内搭后较利落，衣摆不容易左右晃动。"],"cautions":["重点检查腋下，内搭袖子不能被袖笼夹住。"]},{"axis":"fit_type","value":"loose","name":"宽松版型","pros":["能容纳较厚内搭，换季叠穿余量更大。"],"cautions":["袖笼过大会露出较多内搭，不能只看前胸覆盖就判断够暖。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["薄棉马甲便于给躯干加一层，手臂不多叠布料。"],"cautions":["棉材质不能说明填充情况，薄织物与夹棉款差别很大。","洗后留意腋下边缘是否缩紧，别继续勉强套厚内搭。"]},{"value":"fleece","name":"摇粒绒","pros":["蓬松、较轻，作中间层时手臂仍能灵活活动。"],"cautions":["袖笼和前襟不能靠绒厚来弥补过大的开口。","绒面通常不等于挡风层，外出有风时另外判断。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常较容易干，日常增减一件方便打理。"],"cautions":["面料成分不能说明是否有填充，要翻看内侧结构。","拉链和袖笼包边比衣身更可能蹭肤，试穿时一起检查。"]},{"value":"wool","name":"羊毛","pros":["针织羊毛能留住空气，适合给躯干增加保暖。"],"cautions":["腋下和领口可能直接碰到皮肤，要试是否刺痒。","按洗标洗护，不能默认和普通打底衫一起机洗。"]}]'::jsonb),
  ('outer_shell', '春秋外套适合出门加、进屋脱。挑选时带着内搭试穿，抬手不绷、袖口不遮手更实用。外套不一定防风防雨，这些性能要看具体说明；领口和帽子处避开抽绳。', '[{"axis":"fit_type","value":"regular","name":"标准版型","pros":["搭配薄内搭时较利落，衣摆不容易妨碍活动。"],"cautions":["试穿时抱臂，确认后背有余量，别只试拉链能否拉上。"]},{"axis":"fit_type","value":"loose","name":"宽松版型","pros":["方便容纳中间层，进出室内也容易穿脱。"],"cautions":["袖子和下摆不能靠反复卷折才能活动，别用加大号代替宽松版型。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["棉布外套可提供比单层打底更多的覆盖。"],"cautions":["是否挡风取决于织法，棉质本身不等于防风。","淋湿后可能较久不干，不能当雨衣使用。"]},{"value":"fleece","name":"摇粒绒","pros":["绒面保留空气，适合干燥、需要保暖的外出场景。"],"cautions":["没有额外挡风层时，冷风可能透过织物。","“春秋外套”只是品类名，厚抓绒进暖屋后仍可能需要脱下。"]},{"value":"polyester","name":"涤纶","pros":["洗后较容易干，出行时换洗相对方便。"],"cautions":["防水、防风均要看具体结构与说明，不能只看成分。","里侧涂层或接缝较硬时，确认不会蹭到脖子和手腕。"]},{"value":"wool","name":"羊毛","pros":["含毛织物可提供保暖覆盖，适合较凉时外穿。"],"cautions":["厚重程度差别很大，抱起或抬手试试是否压着肩臂。","雨淋后按洗标晾干，别直接高温烘烤。"]}]'::jsonb),
  ('outer_cotton', '棉衣适合较冷时作外层，名称里的“棉”不代表填充物一定是棉花。选购时分开看面料、里料和填充成分，屈肘、抱臂试试是否臃肿。厚蓬款坐安全座椅前要脱下。', '[{"axis":"fit_type","value":"regular","name":"标准版型","pros":["整体较利落，厚填充之外少一些多余布料。"],"cautions":["穿着内搭屈肘、抱臂，确认不是只能垂手站着。"]},{"axis":"fit_type","value":"loose","name":"宽松版型","pros":["叠穿有余量，内搭不容易被前襟挤紧。"],"cautions":["棉衣本身已有厚度，别再用过大尺码堆出臃肿袖子。"]}]'::jsonb, '[{"value":"cotton","name":"棉面料","pros":["棉布表层可吸收少量水分，触感与光滑化纤不同。"],"cautions":["这里说的是面料，不能推断里面填的是棉花。","表层湿了也要检查里层，别把表面干了当作整件干透。"]},{"value":"polyester","name":"涤纶面料","pros":["表层通常较易干，日常擦洗、晾晒较方便。"],"cautions":["面料与填充物要分开看，涤纶面料不代表聚酯填充。","表层干得快不代表厚填充也已干透，收纳前检查整件。"]}]'::jsonb),
  ('outer_down', '羽绒服适合寒冷时在户外穿，挑选要一起看充绒量、绒子含量和衣服大小，不能只比蓬松度。试穿时里面留好叠穿空间；坐安全座椅前脱去厚蓬外层，进暖屋后及时减衣。', '[{"axis":"thickness","value":"lightweight","name":"轻量款","pros":["收纳体积通常较小，临时增减一件更方便。"],"cautions":["“轻量”不是温度承诺，长时间在冷风中停留要重新判断是否够暖。"]},{"axis":"thickness","value":"regular_fill","name":"常规充绒款","pros":["相对轻量款通常更蓬松，适合需要增加外层保暖时比较。"],"cautions":["不同尺码和品牌的“常规”不能直接相比，要看实际充绒信息。"]},{"axis":"thickness","value":"extreme_cold","name":"极寒款","pros":[],"cautions":["厚填充会增加体积，试试宝宝能否自然弯臂和坐下。","“极寒”是款式名称，不能当作保证适用某个温度的依据。"]},{"axis":"fit_type","value":"regular","name":"标准版型","pros":["外形较利落，日常穿脱时少一些多余衣量。"],"cautions":["带着实际内搭试穿，别让前胸和肩背把填充层压得太紧。"]},{"axis":"fit_type","value":"loose","name":"宽松版型","pros":["能为中间层留位置，减少叠穿后挤压。"],"cautions":["袖口过长会遮手，领口过松也影响覆盖，宽松要留在衣身。"]}]'::jsonb, '[{"value":"down","name":"羽绒填充","pros":["蓬松填充能留住空气，以较轻的重量增加保暖。"],"cautions":["绒子含量、充绒量和尺码要一起看，单项数字不能代表整件暖度。","羽绒受潮后蓬松会受影响，洗后按洗标彻底干燥。"]}]'::jsonb),
  ('pants_short', '短裤适合温暖环境下活动，裤腿不拖地，穿脱也方便。挑选时让宝宝坐下、蹲下，检查腰头和裆部；经常爬行时，短裤覆盖不到膝盖，要留意地面和摩擦情况。', '[]'::jsonb, '[{"value":"cotton","name":"棉","pros":["薄棉布可吸收少量汗液，适合温暖时穿着。"],"cautions":["湿后可能贴腿，玩水后的短裤要换下。","棉布不一定有弹性，蹲坐时尤其要看裆部余量。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常较易干，外出沾水后的换洗较方便。"],"cautions":["不等于泳裤或速干裤，这些用途要有具体设计支持。","较硬的裤口可能蹭腿，坐下时摸摸大腿接触处。"]}]'::jsonb),
  ('pants_long', '长裤能覆盖腿部，爬行或外出时较实用。买前让宝宝蹲下、跨步，检查裆部和膝盖是否绷紧；裤脚不要拖地。还穿尿布时把尿布算进尺码，别用过大的裤长来换裆部空间。', '[{"axis":"pant_length","value":"nine_tenth","name":"九分款","pros":["裤口离鞋面较远，少一些脚踝处的堆叠。"],"cautions":["坐下时露出的脚踝会更多，较冷时要连同袜长一起考虑。"]},{"axis":"pant_length","value":"full_length","name":"全长款","pros":["覆盖到脚踝附近，坐下时腿部也能多保留一些覆盖。"],"cautions":["裤脚别拖地或踩在脚下，太长应换尺码或改短。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["可吸收少量汗液，适合日常腿部覆盖。"],"cautions":["裤脚沾水后可能较久不干，要留意脚踝附近是否湿着。","爬行和蹲坐需要余量，棉含量不能说明弹性。"]},{"value":"fleece","name":"摇粒绒","pros":["绒面能留住空气，适合需要腿部保暖时穿。"],"cautions":["普通绒面不一定挡风，风大时别只摸厚度判断。","裤腿过宽再配厚绒，膝后可能堆积，蹲下试试。"]},{"value":"polyester","name":"涤纶","pros":["洗后较容易干，裤脚经常弄脏时便于换洗。"],"cautions":["不是所有涤纶长裤都适合运动，伸展性要实际试。","如果内里有涂层，检查腿部活动时是否僵硬、摩擦。"]}]'::jsonb),
  ('tshirt_short', '短袖 T 恤方便与裤装分开穿脱，练习自己如厕时也省事。领口要容易套过头，抬手后衣摆别卷到胸前。刚开始爬行的宝宝，可多留意抱起、翻身时腰间的覆盖。', '[{"axis":"fit_type","value":"regular","name":"标准版型","pros":["衣身余量适中，外面加薄外套时不容易堆成一团。"],"cautions":["抬手后看看下摆是否卷起，别只看站着时的长度。"]},{"axis":"fit_type","value":"loose","name":"宽松版型","pros":["肩背留量较多，伸手、抱臂时更从容。"],"cautions":["宽松不等于买大号，领口别滑到肩外，袖口也别影响抓握。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["轻薄棉 T 恤能吸汗，日常贴身穿较实用。"],"cautions":["出汗多时湿布可能贴住后背，吸汗不能代替换衣。","印花覆盖面积大时，先摸摸印花内侧是否厚硬。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常较快干，频繁清洗时方便周转。"],"cautions":["“涤纶”不能保证凉感，先看面料厚薄和织得密不密。","大面积贴膜印花会改变局部触感，别只摸没有印花的地方。"]}]'::jsonb),
  ('tshirt_long', '长袖 T 恤适合单穿，也能作外套里面的一层。挑选时让宝宝伸手、抱臂，确认肩背不绷、袖口不盖住手掌；领口和肩部开扣比单纯买大一码更能方便穿脱。', '[{"axis":"fit_type","value":"regular","name":"标准版型","pros":["套在外衣里较利落，手臂处少一些布料堆叠。"],"cautions":["伸直手臂时袖口别往上绷，弯肘时腋下也要有余量。"]},{"axis":"fit_type","value":"loose","name":"宽松版型","pros":["单穿时肩背有余量，活动幅度大时不易牵扯衣身。"],"cautions":["过长的袖子容易沾水、遮手，试穿时把双手伸出来看。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["薄棉布适合打底，能吸收少量汗液。"],"cautions":["袖口沾水后不一定很快干，洗手后留意是否一直湿着。","按洗标洗护，缩水后袖长和肩背余量都可能减少。"]},{"value":"polyester","name":"涤纶","pros":["相同条件下通常比吸水多的棉布更容易晾干。"],"cautions":["领口和袖口贴肤时间长，要单独摸一摸是否粗硬。","外面叠穿较厚时，不能因面料轻就忽略闷热感。"]}]'::jsonb),
  ('thermal_top', '秋衣是贴身打底的一层，适合确实需要叠穿时使用。先看接缝是否平整，再检查腋下和领口；贴合不等于紧勒。外面还要套衣服，别只顾厚度而把手臂裹得难以弯曲。', '[{"axis":"fit_type","value":"slim","name":"紧身版型","pros":["贴合的衣身便于外面叠穿，少一些褶皱。"],"cautions":["贴合以不勒为准，领口、腋下不应留下明显压痕。","不要为了贴身买小一码，先确认胸背和手臂能自由活动。"]},{"axis":"fit_type","value":"regular","name":"标准版型","pros":["给贴身层留出一些空间，穿脱时更好把手臂伸进袖子。"],"cautions":["外套上后摸一摸腋下，打底布料别堆成硬褶。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["可吸收少量汗液，适合喜欢棉布触感的贴身打底。"],"cautions":["运动后湿了要换，别让湿打底被外衣一直盖住。","厚实棉布不一定弹性好，屈肘试试腋下是否绷紧。"]},{"value":"polyester","name":"涤纶","pros":["带导湿结构的款式有利于把汗带向外侧。"],"cautions":["这一优点取决于面料设计，普通涤纶不能直接当导湿内衣。","贴身层重点检查接缝和领口，柔软衣身不代表整件都不磨。"]}]'::jsonb),
  ('outer_uv', '防晒衣适合户外遮挡，不能凭“薄”或“冰凉”判断防晒效果。看明确的防晒性能标识，也看袖长和领口的覆盖；不满六个月的宝宝更应避开阳光直晒，不能靠多穿一件来延长暴晒时间。', '[]'::jsonb, '[{"value":"cotton","name":"棉","pros":["轻薄棉布能吸收少量汗液，触感适合日常穿着。"],"cautions":["棉成分不保证防晒性能，要看明确标识。","汗湿后布料可能贴身，不宜只追求薄而忽略实际穿着感受。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常较容易干，适合出门随身携带、反复换洗。"],"cautions":["不能把涤纶与防晒等级直接画等号，查看成衣性能说明。","覆膜或紧密织面可能偏闷，试穿时留意腋下和背部。"]}]'::jsonb),
  ('long_johns', '秋裤适合作为裤装里面的一层，需要时再加。穿尿布的宝宝要留裆部余量，已经自己如厕的宝宝可选好拉下的腰头。试试蹲下和抬腿，别让双层腰头一起勒住肚子。', '[{"axis":"fit_type","value":"slim","name":"紧身版型","pros":["贴合腿部，外穿裤子时不容易堆褶。"],"cautions":["蹲下后腰头、膝后不能勒紧，弹性大也不能代替合适尺码。"]},{"axis":"fit_type","value":"regular","name":"标准版型","pros":["腿部留有余量，拉上、脱下时较顺手。"],"cautions":["外穿裤子后检查膝后和裆部，别让两层布料挤成一团。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["棉布能吸收少量汗液，适合贴腿穿着。"],"cautions":["尿湿或汗湿后应换下，不能靠外裤遮着继续穿。","洗后可能缩水，膝部和裆部不要选得刚好绷紧。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常较易干，换洗频繁时较方便。"],"cautions":["普通涤纶不一定导湿，别将成分当成功能承诺。","腿部整天贴着布料，先检查膝后和裆缝是否平整。"]}]'::jsonb),
  ('pants_mid', '中裤适合想少露一些腿、又不需要全长裤时穿。不同身高穿出的长度差很多，别只看“中裤”名称；试穿时弯膝，确认裤口没有卡在膝盖附近，坐下后腰头也不紧。', '[{"axis":"fit_type","value":"regular","name":"标准版型","pros":["裤腿较利落，活动时多余布料较少。"],"cautions":["坐下、弯膝试试裤口，别正好卡住膝部。"]},{"axis":"fit_type","value":"loose","name":"宽松版型","pros":["臀部和大腿有余量，蹲坐时更好伸展。"],"cautions":["宽松裤腿不等于腰头宽松，腰围和裤口都要分别试。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["薄棉布适合日常活动，能吸收少量汗液。"],"cautions":["膝部附近反复弯折，试试裤口包边会不会卡住或磨蹭。","棉材质不代表柔软有弹性，厚织布需要更多活动余量。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常较快干，活动后常换洗较方便。"],"cautions":["厚度和织法会影响闷热程度，不能只看“轻”。","裤口若正好在膝部，接缝硬度比衣身触感更值得检查。"]}]'::jsonb),
  ('shoes_sandal', '会在户外走路后，再按场景选凉鞋；还不会走路时不必为了练走而穿鞋。挑选时看后跟能否固定、鞋底是否好弯折，再摸鞋带边缘。试走几步，别只凭坐着时“能穿进去”判断。', '[]'::jsonb, '[]'::jsonb),
  ('shoes_sneaker', '运动鞋适合户外走路、玩耍时保护脚部，学步并不靠鞋来训练。选前掌能弯、脚趾有活动空间的款式，让宝宝站起来试走；在安全、温暖的室内，也可以赤脚活动。', '[{"axis":"thickness","value":"standard","name":"标准款","pros":["相较大面积网眼款，鞋面覆盖通常更多，日常外出较通用。"],"cautions":["“标准”不代表防水，下雨天是否适用要另看说明。"]},{"axis":"thickness","value":"breathable","name":"透气款","pros":["有透气网眼的鞋面便于空气流通，适合温暖时活动。"],"cautions":["网眼处容易进水、沙粒，玩沙后要脱鞋检查。"]}]'::jsonb, '[]'::jsonb),
  ('shoes_leather', '皮鞋适合需要搭配的场合，但名称不能说明整双鞋的柔软度或成分。已经会走路的宝宝，先试前掌弯折、脚趾空间和后跟贴合；穿着好看，不能替代实际走几步的检查。', '[{"axis":"thickness","value":"standard","name":"标准款","pros":["没有额外绒里，试穿时更容易判断鞋内空间。"],"cautions":["别预留过大的“长脚空间”，后跟滑动会影响走路。"]},{"axis":"thickness","value":"fleece_lined","name":"加绒款","pros":["绒里增加脚部包覆，较冷时可作为选项。"],"cautions":["绒里会占掉鞋内空间，要穿着实际搭配的袜子试走。"]}]'::jsonb, '[]'::jsonb),
  ('shoes_boot', '高帮靴适合需要更多脚踝覆盖的外出场景，不是学步必需品。试穿时走路、蹲下，检查靴筒是否顶腿、后跟是否滑动；靴子不一定防水，雨雪用途要看明确说明。', '[{"axis":"thickness","value":"standard","name":"标准款","pros":["没有绒里堆叠，脚踝处通常少一些厚度。"],"cautions":["靴筒较高也未必适合学步，蹲下时不能顶住小腿。"]},{"axis":"thickness","value":"fleece_lined","name":"加绒款","pros":["脚面和脚踝多一层包覆，适合需要增加保暖时比较。"],"cautions":["袜子再加厚可能挤脚，先检查脚趾能否舒展。","内里受潮后要充分晾干，不能只看外面已经干了。"]}]'::jsonb, '[]'::jsonb),
  ('socks', '袜子主要用来覆盖脚部、减少鞋内摩擦，尺码要看脚长，不只看月龄。穿上后脚趾能舒展、袜口不明显勒腿。练习走路时，光滑地面上要留意袜底是否打滑。', '[{"axis":"sock_height","value":"no_show","name":"船袜","pros":["袜口较低，露踝鞋里不容易堆出一圈袜筒。"],"cautions":["走几步看后跟是否滑落，滑进鞋内的袜子更容易起褶。"]},{"axis":"sock_height","value":"ankle","name":"短筒袜","pros":["能覆盖鞋口附近，减少鞋边直接接触皮肤。"],"cautions":["搭高帮鞋时袜筒可能不够高，先对照鞋口位置。"]},{"axis":"sock_height","value":"mid_calf","name":"中筒袜","pros":["覆盖脚踝上方，配长裤时衔接较稳定。"],"cautions":["袜筒别层层卷下，堆在脚踝处反而容易勒。"]},{"axis":"sock_height","value":"over_calf","name":"长筒袜","pros":["腿部覆盖更多，短一些的裤装下也能补充覆盖。"],"cautions":["袜口不要勒在膝窝处，弯腿后也要检查。","别靠买小号防下滑，脚趾空间会一起变小。"]}]'::jsonb, '[{"value":"cotton","name":"棉","pros":["可吸收脚部少量汗液，减少直接接触鞋内衬。"],"cautions":["汗湿后袜子不一定快干，脱鞋时顺便检查是否潮湿。","袜子常含弹性纤维，别仅凭“棉袜”就判断是全棉。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常较易干，换洗周转方便。"],"cautions":["排汗效果取决于织法，不是所有涤纶袜都能把汗带走。","脚趾缝头和袜口弹力要单独检查，别只摸袜底厚薄。"]}]'::jsonb),
  ('scarf', '围巾只在需要颈部覆盖时使用，选短而利落、没有长流苏的款式。宝宝还不会自己整理衣物时，更要留意是否遮住口鼻或缠住颈部；玩攀爬设施前取下，睡觉时不用。', '[]'::jsonb, '[{"value":"cotton","name":"棉","pros":["薄棉织物可提供颈部覆盖，适合不喜欢毛感的孩子。"],"cautions":["口水打湿后要换下，别一直裹着湿布。","厚棉围巾层层绕会增加颈部体积，先看系好后的松紧。"]},{"value":"fleece","name":"摇粒绒","pros":["绒面较轻，适合较冷时补充颈部覆盖。"],"cautions":["绒厚也不能堆到口鼻前，活动时检查位置。","是否挡风仍要看织物结构，不能只认绒面。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常较易干，常被口水弄湿时方便换洗。"],"cautions":["实际触感可能光滑也可能粗硬，贴颈处要逐段摸。","干得快不意味着能继续戴湿的，打湿后及时换下。"]},{"value":"wool","name":"羊毛","pros":["蓬松纤维能留住空气，适合补充颈部保暖。"],"cautions":["脖颈直接接触处先试是否扎，不宜只隔着衣服摸。","按洗标清洗，缩水后长度、宽度都可能变化。"]}]'::jsonb),
  ('gloves', '手套适合较冷时在户外保护双手。选腕口不勒、内部没有线圈缠手指的款式，戴上后试试抓握。玩水或雪后检查是否湿透；不靠连接长绳防丢，避免活动时被勾住。', '[]'::jsonb, '[{"value":"cotton","name":"棉","pros":["棉布触感适合轻度手部覆盖，薄款较便于抓握。"],"cautions":["吸水后不易马上干，不适合只靠它长时间玩水或雪。","戴上后检查指尖空间，棉布不一定能弹性伸展。"]},{"value":"fleece","name":"摇粒绒","pros":["重量较轻，绒面能给双手增加保暖。"],"cautions":["普通绒面不防水，湿透后要换下。","厚绒会占手掌空间，让宝宝抓一下物品再决定尺码。"]},{"value":"polyester","name":"涤纶","pros":["洗后通常较容易干，日常换洗较方便。"],"cautions":["成分不等于防水，玩雪用途要另看外层和接缝设计。","里缝可能磨到手指，买前翻看内侧并检查线头。"]},{"value":"wool","name":"羊毛","pros":["蓬松纤维适合作为手部保暖层。"],"cautions":["手腕和指缝处要试是否刺痒，细腻程度因织物而异。","不能因含羊毛就当作防水手套，湿了仍需换下。"]}]'::jsonb),
  ('vest_down', '羽绒马甲适合较冷时给躯干增加保暖，手臂仍由内搭覆盖。挑选时看充绒说明和腋下余量，不只看鼓不鼓。坐安全座椅前脱去厚蓬外层，再贴身扣紧安全带。', '[{"axis":"fit_type","value":"regular","name":"标准版型","pros":["衣身较利落，手臂活动时不易带动整件衣服。"],"cautions":["扣好前襟再抬手，里面的打底不能被腋下夹紧。"]},{"axis":"fit_type","value":"loose","name":"宽松版型","pros":["里面加毛衣时有余量，填充层不容易被挤扁。"],"cautions":["不是越宽越暖，领口和袖笼张得过大时覆盖会变少。"]}]'::jsonb, '[{"value":"down","name":"羽绒填充","pros":["以较轻的重量提供蓬松保暖，适合冷天给躯干加一层。"],"cautions":["羽绒是填充物，不能据此判断外面的布料是否防水。","受潮会影响蓬松，洗后按洗标充分干燥再收纳。"]}]'::jsonb),
  ('hat', '帽子按用途选：遮阳看帽檐覆盖，保暖看耳部和头围是否合适。戴上后不能挡眼，也别靠勒紧固定。宝宝进入温暖室内后取下保暖帽，睡觉时不戴帽子。', '[{"axis":"hat_kind","value":"sun","name":"遮阳帽","pros":["宽帽檐或后部遮片能增加脸、耳和颈部的遮挡。"],"cautions":["只遮前额的窄帽檐覆盖有限，试戴时看看耳后和颈后。"]},{"axis":"hat_kind","value":"everyday","name":"日常帽","pros":[],"cautions":["按实际用途看帽檐和厚度，不能把“日常帽”当成防晒或保暖保证。"]},{"axis":"hat_kind","value":"warm","name":"保暖帽","pros":["覆盖头部，护耳设计还能减少耳部直接暴露。"],"cautions":["不要遮住眼睛或口鼻；进暖屋、睡觉时取下。"]}]'::jsonb, '[]'::jsonb)
on conflict (category_code) do update set
  intro = excluded.intro,
  style_guides = excluded.style_guides,
  material_guides = excluded.material_guides,
  updated_at = now();

grant select on public.category_guide_contents to anon, authenticated;
